### PR TITLE
tring → string (typo fix)

### PR DESCRIPTION
**Pull request by gimbles**

### CODE REVIEW

**Comment by gimbles** [comment]
The.. check seems unrelated to my changes?

**Comment by zesterer** [comment]
Thanks! Looks like it might need a fmt pass or something?

**Comment by m-hugo** [comment]
> Thanks! Looks like it might need a fmt pass or something?

?, it's a clippy error, since https://github.com/rust-lang/rust-clippy/pull/10520 it thinks src/private.rs:280:18 is UB
280 |         unsafe { MaybeUninit::uninit().assume_init() }

**Comment by zesterer** [comment]
> it thinks src/private.rs:280:18 is UB

That's frustrating. It would be nice if clippy checked the self type.

**Comment by zesterer** [comment]
This is now fixed on main, so after a rebase CI should pass.

**Comment by gimbles** [comment]
Merged, should pass CI now

**Pull request merged**
