### PR TITLE
:zap: Add nom to cbor benchmark

### PR DESCRIPTION
**Pull request by homersimpsons**
```
$ cargo bench cbor
   Compiling chumsky v1.0.0-alpha.6 (/workspaces/chumsky)
    Finished bench [optimized + debuginfo] target(s) in 57.71s
     Running unittests src/lib.rs (target/release/deps/chumsky-7015145845c85ce9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 29 filtered out; finished in 0.00s

     Running benches/backtrack.rs (target/release/deps/backtrack-17ad3cadf2b60b4d)
     Running benches/cbor.rs (target/release/deps/cbor-699359807057cadd)
cbor_nom                time:   [162.80 µs 168.21 µs 174.98 µs]
Found 18 outliers among 100 measurements (18.00%)
  8 (8.00%) high mild
  10 (10.00%) high severe

cbor_chumsky_zero_copy  time:   [301.61 µs 312.44 µs 324.93 µs]
Found 15 outliers among 100 measurements (15.00%)
  3 (3.00%) high mild
  12 (12.00%) high severe

cbor_chumsky_zero_copy_check
                        time:   [129.18 µs 135.44 µs 143.41 µs]
Found 19 outliers among 100 measurements (19.00%)
  7 (7.00%) high mild
  12 (12.00%) high severe

cbor_ciborium           time:   [599.69 µs 615.76 µs 634.66 µs]
Found 15 outliers among 100 measurements (15.00%)
  4 (4.00%) high mild
  11 (11.00%) high severe

     Running benches/json.rs (target/release/deps/json-47342f2651c0ce44)
     Running benches/lex.rs (target/release/deps/lex-10701e529003bbe2)
     Running benches/parser.rs (target/release/deps/parser-187efd51a1f4382a)
     Running benches/utils.rs (target/release/deps/utils-9586bc81ca871d76)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

The benchmarks were run inside GitHub Codespace, so take the the numbers with a grain of salt.

I did try to stick close to chumsky's implementation, in particular I did not add handling of "undefined length" elements, nor handling of some CBOR data types that were not handled.

### CODE REVIEW

**Comment by homersimpsons** [comment]
I just wanted to try to implement CBOR with nom, this may be relevant to have it here.

References:
- https://fr.wikipedia.org/wiki/CBOR
- https://github.com/Nullus157/cbor-diag-rs/blob/main/src/parse/binary.rs
- The existing chumsky implementation
- The exisitng json-nom implementation

**Comment by zesterer** [comment]
Looks good at first glance, maybe @CraftSpider has thoughts?

**Comment by CraftSpider** [comment]
Sorry for the delay, was out walking on a beach most of yesterday :P

Anyways, this looks good to me. I'm not incredibly familiar with nom, but overall the implementation looks fine. I would like to fix the mentioned fact that the test only has some types at some point - currently it was created from the JSON test, so only takes advantage of stuff that exactly matches what JSON can do.

**Comment by zesterer** [comment]
Thanks for the PR!

**Pull request merged**
