### PR TITLE
Use diagnostic namespace, make message appear on ParserSealed mismatches

### PR DESCRIPTION
**Pull request by CraftSpider**
This should slightly improve the situation for trait errors. We don't get *too* much control over the diagnostic, but I tried to push the bits important to the front.

### CODE REVIEW

**Comment by CraftSpider** [comment]
Note that this will be an MSRV bump when it happens, but that the on_unimplemented diagnostic is *currently* in FCP to stabilize. That isn't a guarantee obviously, but it's a lot more likely to stabilize than a `rustc_attr`, which never will.

**Comment by zesterer** [comment]
Awesome!

**Review by zesterer — APPROVED** [review]
You have merge perms, right?

**Comment by CraftSpider** [comment]
I do - I'll merge this, then probably make another thing to fix the check build.

**Pull request merged**
