### PR TITLE
Add `state` to pratt parser

### PR DESCRIPTION
**Pull request by ojkelly**
I recent updated, and needed to adjust a bunch of code for #537. I think it makes sense to reduce those to one `map_with`, however spending a few hours on it, I couldn't quite work out how to achieve the same here.

I tried passing a `MapExtra` instead of `span` and `state`. I got stuck on lifetime issues from nested closures, and loosing type inference on what `state` is.

Perhaps there's a way to make it work, but in the mean time this has unblocked me.

### CODE REVIEW

**Comment by zesterer** [comment]
Thanks for the contribution! `MapExtra` is quite a new addition (as in: last week) so the pratt combinator has not been updated. I think this contribution is definitely *behaviourally* correct, but I think I'll hold off on merging it pending an attempt to make the pratt combinator support `MapExtra`. Thanks!

**Comment by ojkelly** [comment]
> but I think I'll hold off on merging it pending an attempt to make the pratt combinator support `MapExtra`. Thanks!

Sounds good, if you can get `MapExtra` working that would be better.

**Comment by zesterer** [comment]
I've added support in #553, hopefully this works for your use-case!

**Comment by ojkelly** [comment]
Thanks! So that PR is what I had tried, but as it turns out I had somewhere else unintentionally constraint the type returned by a parsing function.

After wrangling all those, it's working.

I do still need to type it, but after rewriting the outer fn sig to get access to the Input and Extra generics inside the function it's working.

```rust
    expr.pratt((
      pratt::prefix(
        2,
        lexer::control::spanned_sub(),
        |op_token, rhs, e: &mut Extra<'tokens, '_, I, E>| {
          let span: Span = e.span();
          let state: &mut State = e.state();
          state.insert(crate::Node::ExpressionInlineOpNegative(
            Negative {
              span,
              op_token,
              rhs,
            },
          ))
        },
      ),
```

**Comment by zesterer** [comment]
Yes, the need to add a type annotation is an unfortunate issue. It's a product of `rustc`'s weak inference algorithm that requires types to be fully known when calling methods on them or performing field accesses.

I say `rustc` and not 'Rust' more generally because `mrustc`, the Rust compiler written in C++, actually has a stronger constraint-based inference algorithm that *can* deal with cases like this.

If you want a neater way to write this inline, you can do

```rs
(e.state() as &mut State).insert(...);
```

Also, `span` shouldn't need an annotation here since no methods are being called on it.

**Comment by ojkelly** [comment]
Ooh, I didn't think of doing that for the inline syntax, that is nice.

Yep dropping the span type works as well, I thought I needed it because it's a custom type, but it's all inferred well enough.

**Pull request closed without merging**
