### PR TITLE
Add foldl_with_state and foldr_with_state

### PR DESCRIPTION
**Pull request by MechSlayer**

### CODE REVIEW

**Review by zesterer — COMMENTED** [review]
Thanks! The implementation looks great. Is there any chance you could put something like `// TODO: Add examples of interning/arena allocation` below both of the doc comments for `Parser::fold[l/r]_with_state`?

**Comment by MechSlayer** [comment]
Done, also changed the examples to since they were invalid @zesterer

**Comment by zesterer** [comment]
Seems like inference is failing for the tests, I imagine you need to specify the missing type parameter.

**Comment by MechSlayer** [comment]
My bad, still pretty new to Rust, didn't know that docs actually get compiled and act as tests

**Pull request merged**
