### PR TITLE
Add then_with combinator

### PR DESCRIPTION
**Pull request by CraftSpider**
Includes the two notes I thought important: That `or` is preferred if possible, and the warning about suboptimal errors. The `ThenWith` type requires the extra generics due to issues on the impl otherwise regarding unbound generics.

### CODE REVIEW

**Comment by CraftSpider** [comment]
Note: Could also change the resulting parser to `(I, U)` to match `then`, if we passed a reference to the parsed value (perhaps a mutable one) instead of ownership. Not sure which would be preferred.

**Comment by zesterer** [comment]
Hopefully I will have time to review this tonight.

**Comment by zesterer** [comment]
Narrator: *He did not...*

Tonight, then.

**Comment by zesterer** [comment]
Thanks, this looks good!

**Pull request merged**
