### PR TITLE
This is your reminder to merge the two tutorial chunks

### PR DESCRIPTION
**Pull request by Lokathor**
<3

### CODE REVIEW

**Comment by Lokathor** [comment]
Hey @zesterer ping ya gotta merge this or it'll stay in my github PR list forever

**Comment by zesterer** [comment]
I'm not sure what action to take here. I think your additions are good in isolation (particularly as an independent guide for each primitive), but they're not comprehensive enough alone and only cover a small part of the tutorial page. As a result, I don't think this is in a position to merge yet, and I don't currently have time right now to take your work and add 'the rest of the owl' for it to be mergeable.

**Comment by Lokathor** [comment]
Well, if you don't want to just merge the file and have the partial for for later I'll just close it then. If you still want to use any of the words they'll be in the PR's diff view thing when you get the time.

**Comment by zesterer** [comment]
I hope I can find the time to integrate most of your changes. Life has been busy recently :(

**Pull request closed without merging**
