### PR TITLE
[zero-copy] Update choice impl a little, add array impl from master

### PR DESCRIPTION
**Pull request by CraftSpider**
Small benchmarks say this is a minor improvement. Big benchmark doesn't change, but it's dominated by other parsers anyways.

### CODE REVIEW

**Comment by zesterer** [comment]
Nice catch!

**Comment by zesterer** [comment]
Holy smokes. 'Minor improvement'?!

image

**Comment by Zij-IT** [comment]
I'm starting to think that some people and I have very different definitions of 'minor' ;P

**Comment by CraftSpider** [comment]
Oh damn, I did the just choice and the json benchmark, didn't remember the lex one. That's a nice improvement.

**Pull request merged**
