### PR TITLE
Solution to fix ahash version error

### PR DESCRIPTION
**Pull request by GPeaky**

### CODE REVIEW

**Comment by GPeaky** [comment]
Sorry i didn't put any information here. all the information is in this issue:
https://github.com/zesterer/chumsky/issues/555

sorry if i do something bad in github, i still learning about how to contribute 😞

**Comment by zesterer** [comment]
Thanks!

**Comment by zesterer** [comment]
Are you looking for a new version with this?

FWIW, I would recommend moving to one of the 1.0 alpha releases for any new work.

**Comment by wackbyte** [comment]
In #555 they use the `lettre` crate which depends on `^0.9.0` :)

**Comment by GPeaky** [comment]
> Are you looking for a new version with this?
> 
> 
> 
> FWIW, I would recommend moving to one of the 1.0 alpha releases for any new work.

Yeah am looking for 9.3 to open an issue in Letre to use 9.3 instead of 9.0 to fix this error cause now I cannot install lettre.

It's the alpha release totally compatible with 0.9?, and i probably think they will prefer to still using a release version

**Comment by paolobarbolini** [comment]
> Are you looking for a new version with this?
> 
> FWIW, I would recommend moving to one of the 1.0 alpha releases for any new work.

We're looking into updating but there's no changelog for the 1.0 alpha releases and commits aren't tagged so it'll take a while. If you can backport the hashbrown upgrade I'd suggest doing so.

**Comment by zesterer** [comment]
> It's the alpha release totally compatible with 0.9?

No, not at all. `1.0` is an almost from-scratch rewrite of the crate and some of the fundamental concepts (such as the way inputs have handled) have changes to allow for things like nested inputs, zero-copy parsing, etc. You might find [the guide](https://docs.rs/chumsky/1.0.0-alpha.6/chumsky/guide/index.html) to be useful. It's worth making the jump though: `1.0` is substantially faster and far more capable in innumerable ways.

> We're looking into updating but there's no changelog for the 1.0 alpha releases and commits aren't tagged so it'll take a while.

I meant a new `0.9.6` release. The `1.0` released (and the `main` branch) don't have this issue so should be unaffected.

**Comment by GPeaky** [comment]
Perfet, if you could update this to fix this patch error

**Comment by zesterer** [comment]
`0.9.3` has now been released.

**Comment by GPeaky** [comment]
That's perfect, i already try it and its working now!, thanks

**Pull request merged**
