### PR TITLE
Added optional `span:ident` argument to `select!`

### LINKED ISSUE #101: Support mapping with span in `select!`
Support this kind of syntax:

```rust
select! { span,
    Token::Word(w) => AstNode { span, ast: AstKind::Word(w) }
    Token::KeyWord(kw) => AstNode { span, ast: AstKind::KeyWord(kw) }
}
```

### PR DESCRIPTION
**Pull request by JohnDowson**
Closes #101

### CODE REVIEW

**Comment by zesterer** [comment]
I think I would prefer if this were implemented as an optional attribute that bound for each pattern, like so:

```rs
select! {
    Foo(foo), span => f(foo, span),
    Bar(bar) => bar,
}
```

This feels a lot cleaner to me. Are you okay if I reimplement this?

**Comment by JohnDowson** [comment]
> This feels a lot cleaner to me.

While it does look cleaner, i'm not sure if it's practival.
Given you can only return one type from each branch, you are likely to either need span in all or none of them.

**Comment by zesterer** [comment]
I think having an API that looks visually consistent and obvious is more important than needing to type a few extra characters, personally. Perhaps there is an alternative design that fulfils both objectives, but I don't really see it.

**Comment by JohnDowson** [comment]
Perhaps something like this?
```rust
select! {
    span => ident,
    Token::Word(w) => AstNode { span, ast: AstKind::Word(w) }
    Token::KeyWord(kw) => AstNode { span, ast: AstKind::KeyWord(kw) }
}
```

**Comment by zesterer** [comment]
That's ambiguous syntax (`span` is itself a valid pattern).

**Comment by JohnDowson** [comment]
> That's ambiguous syntax (`span` is itself a valid pattern).

Well, you could use `;` instead of `,` for span binding. Either way, that's your library, I'll be happy if this feature exists in whatever form you choose.

**Comment by zesterer** [comment]
I've implemented this in 0d7e72a along with an example. Hopefully this is sufficient for your use-case!

**Pull request closed without merging**
