### PR TITLE
[zero-copy] Add nom benchmark

### PR DESCRIPTION
**Pull request by wackbyte**
Adds a benchmark for nom based on the example linked in #89.

### CODE REVIEW

**Comment by wackbyte** [comment]
(here are the results I got on my Ryzen 5 3600X)
image

**Comment by zesterer** [comment]
Holy heck! `chumsky/zero-copy` zero is *faster* than `nom`?! That I did not expect in the slightest. Obviously that's going to take a bit of a beating when proper error reporting is implemented, but hopefully most of the performance wins can be preserved.

**Comment by zesterer** [comment]
Holy heck! `chumsky/zero-copy` zero is *faster* than `nom`, even without an explicit `escaped` primitive?! That I did not expect in the slightest. Obviously that's going to take a bit of a beating when proper error reporting is implemented (although the error handling the branch has right now is still roughly equivalent to `nom`'s), but hopefully most of the performance wins can be preserved.

**Comment by zesterer** [comment]
As a confirmation, I'm seeing similar numbers locally.

image

**Pull request merged**
